version: "3"
services:
  signature_prometheus:
    image: prom/prometheus:latest
    container_name: infra-prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    network_mode: ${SIGNATURE_NETWORK}
    restart: on-failure
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:    
      - ${PROMETHEUS_CONFIG_FILE_PATH}=/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_CUSTOM_CONFIG_PATH}:/etc/prometheus
      - ${PROMETHEUS_DATA_PATH}:/prometheus
    user: root

  signature_grafana:
    image: grafana/grafana:latest
    container_name: infra-grafana
    ports:
      - ${GRAFANA_PORT}:3000
    network_mode: ${SIGNATURE_NETWORK}
    restart: on-failure
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
    user: root
    depends_on:
      - signature_prometheus

  signature_zipkin:
    image: openzipkin/zipkin-slim
    container_name: infra-zipkin
    ports:
      - ${ZIPKIN_PORT}:9411
    network_mode: ${SIGNATURE_NETWORK}
    restart: on-failure
    depends_on:
      - signature_prometheus

  signature_portainer:
    image: portainer/portainer-ce
    container_name: infra-portainer
    ports:
      - ${PORTAINER_PORT}:9000
    network_mode: ${SIGNATURE_NETWORK}
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  
  signature_portainer_agent:
    image: portainer/agent
    container_name: infra-portainer-agent
    ports:
      - ${PORTAINER_AGENT_PORT}:9001
    network_mode: ${SIGNATURE_NETWORK}
    volumes:
      - ${PORTAINER_AGENT_DATA_PATH}:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure