global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'infra-apigateway-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'infra-apigateway:8360' ]

  - job_name: 'be-signature-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'be-signature:8310' ]

  - job_name: 'be-auth-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'be-auth:8320' ]
      
  - job_name: 'be-wallet-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'be-wallet:8330' ]

  - job_name: 'be-van-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'be-van:8340' ]