version: "3"
services:
  signature_jenkins:
    container_name: infra-jenkins
    image: jenkins/jenkins:jdk17
    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    user: root
    volumes:
      - ${JENKINS_DATA_PATH}:/var/jenkins_home
    restart: on-failure