version: "3"
services:
  signature_mysql:
    container_name: database-mysql
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    network_mode: ${SIGNATURE_NETWORK}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d
    restart: on-failure

  signature_mongodb:
    container_name: database-mongodb
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    network_mode: ${SIGNATURE_NETWORK}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db

  signature_redis:
    container_name: database-redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    network_mode: ${SIGNATURE_NETWORK}
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CUSTOM_CONFIG_PATH}:/usr/local/conf/redis.conf
    restart: on-failure