version: "3"
services:
  signature_nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      # Public HTTP Port
      - 80:80
      # Public HTTPS Port  
      - 443:443
      # Admin Web Port
      - ${NGINX_WEB_PORT}:81
    restart: on-failure
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ${NGINX_DATA_PATH}:/data
      - ${NGINX_SSL_PATH}:/etc/letsencrypt